### PR TITLE
* adding CookieSecurity to built-in security methods

### PR DESCRIPTION
**Pull request by bhoriuchi**
Simple CookieSecurity class

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bhoriuchi** [comment]
I think this got removed by my other PR because  I don't see it in the current master and in PR 40 i removed this code to keep the PR's separate.

**Comment by rashmihunt** [comment]
@bhoriuchi I noticed that too. I only merged PR 37 and I noticed that PR 39 was gone. I can't really merge PR 40 since it's not showing up in PR list and also if I do directly to the link https://github.com/strongloop/strong-soap/pull/40 I don't see anything to merge. Can you resubmit the PR again or create a new PR and resubmit? Can you please add test case with the PR? Thanks!

**Pull request merged**
