### PR TITLE
Fix Issue#114

### PR DESCRIPTION
**Pull request by aladinnnus**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@aladinnnus Sorry for the delay. Can you explain what problem your PR is fixing?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@aladinnnus, I'm closing this PR due to inactivity.  If you'd like to continue working on this PR, please explain what you're trying to accomplish.  Thanks.

**Pull request closed without merging**
