### PR TITLE
handle xsd order correctly

### PR DESCRIPTION
**Pull request by bgdavidx**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@bgdavidx Thank you for the patch. Can you sign the CLA at https://cla.strongloop.com/agreements/strongloop/strong-soap?

**Comment by bgdavidx** [comment]
@raymondfeng  sorry I pushed some other irrelevant commits to my fork last night. made another PR with the xsd fix: https://github.com/strongloop/strong-soap/pull/99

**Pull request closed without merging**
