### PR TITLE
allow xsd:include to include a schema without target namespace

### LINKED ISSUE #137: Elements defined in an included xsd file are not found by the wsdl parser
# Description/Steps to reproduce
First of all, I believe this is a bug. Secondly, as for the steps to replicate the issue, here's the conceptual way to do so:

1. Have a WSDL with external xsd schema file(s) included
2. Create a SOAP client based on that WSDL

And here are the steps based on the provided [test_case.zip](https://github.com/strongloop/strong-soap/files/1606925/test_case.zip):
1. `$ cd test_case`
2. `$ npm install`
3. `$ node ./src/strong-client.js`

What I found myself debugging the code is that, it seems like even though the schema for `rps:ES2-GetEISRequest` is provided in the `euicc.request.ES2.xsd` but it's not accessible to the wsdl's parser at `node_modules/strong-soap/src/parser/element.js:184` where `resolveSchemaObject(schemas, elementType, nsName)` is trying to populate `part.element` with that. This is not resulting in an error on its own. But later, down the line when the `part` is being created, the following error occurs:

```
AssertionError [ERR_ASSERTION]: Document/literal part should use element
    at Operation.getMode (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/operation.js:349:11)
    at Operation.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/operation.js:65:12)
    at Binding.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/binding.js:60:17)
    at Service.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/service.js:22:19)
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:69:25
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:189:9
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:189:9
    at WSDL._processNextInclude (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:157:14)
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:188:12
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:101:9
```

# Link to reproduction sandbox

This is an issue with SOAP client. I'm not sure if a sandbox applies here. In any case, I've attached a [test_case.zip](https://github.com/strongloop/strong-soap/files/1606925/test_case.zip) to the issue.

# Expected result

I couldn't run the code ever to say what exactly it should return but simply put, it should show the loaded `client` as the second parameter of the function's arguments.

# Additional information

It's also worth noting that the provided WSDL file can be used in SOAP-UI without any problems.

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'`
linux x64 9.3.0
$ npm ls --prod --depth 0 | grep loopback
(nothing)
```

### PR DESCRIPTION
**Pull request by raymondfeng**
### Description

Fix #137

#### Related issues

- connect to #137 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by chandrakantpant** [comment]
@raymondfeng i still the similar issue at my end.

I have got below strong-soap package.

 cat package.json
{
  "name": "soapclient",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "strong-soap": "^1.5.0"
  }
}


Wdsl that i am trying is ORACLE BPM serivce
http://host:port/integration/services/TaskQueryService/TaskQueryService?WSDL

and the error that i am getting is 

=======
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
'0'
> var exposedclient = {};
undefined
> soap.createClient(url, {}, function(err, client) {
...   exposedclient = client;
...   console.log('done creating client');
...         console.log(err);
... });
undefined
> AssertionError [ERR_ASSERTION]: Document/literal part should use element
    at Operation.getMode (C:\Users\user\Desktop\soapclient\node_modules\stron
g-soap\src\parser\wsdl\operation.js:349:11)
    at Operation.postProcess (C:\Users\user\Desktop\soapclient\node_modules\s
trong-soap\src\parser\wsdl\operation.js:65:12)
    at Binding.postProcess (C:\Users\user\Desktop\soapclient\node_modules\str
ong-soap\src\parser\wsdl\binding.js:60:17)
    at Service.postProcess (C:\Users\user\Desktop\soapclient\node_modules\str
ong-soap\src\parser\wsdl\service.js:22:19)
    at C:\Users\user\Desktop\soapclient\node_modules\strong-soap\src\parser\w
sdl.js:69:25
    at C:\Users\user\Desktop\soapclient\node_modules\strong-soap\src\parser\w
sdl.js:197:9
    at WSDL._processNextInclude (C:\Users\user\Desktop\soapclient\node_module
s\strong-soap\src\parser\wsdl.js:157:14)
    at C:\Users\user\Desktop\soapclient\node_modules\strong-soap\src\parser\w
sdl.js:196:12
    at C:\Users\user\Desktop\soapclient\node_modules\strong-soap\src\parser\w
sdl.js:101:9
> exposedclient
{}
============

**Comment by wrfarina** [comment]
@chandrakantpant can you give access to the WSDL? The url:
> http://host:port/integration/services/TaskQueryService/TaskQueryService?WSDL

Is not accesible.

I have a similar issue even after this fix, it's a WSDL that imports XSDs but I can't put it here.

**Comment by PaulHindenberg** [comment]
@wrfarina I had the same issue.. and this fix didn't do it as well. But after a few hours, I found the wrongly turned piece of the puzzle. Maybe this will help you as well.

Ok, so I had a few WSDL files to import. Most of them worked perfectly, but for some, I had the same error as in this issue. All of them have some XSD imports though! The problem with those "Error" WSDLs were that the Import for the "Exceptions-XSD" was on Position 1 and the other Definitions were after those -> Position 2,3,... After shifting the import of the "Exception-XSD" to position 2 I was able to load the WSDL file and the error was gone.  

@raymondfeng Shall I open a new issue for this?

**Comment by raymondfeng** [comment]
@PaulHindenberg Yes, please open a new issue with offending wsdl/xsd files.

**Pull request merged**
