### PR TITLE
Updates xml crypto to 2.0.0 in version 1.x-latest

### PR DESCRIPTION
**Pull request by marcosins**
### Description
- Updates `xml-crypto@2.0.0` in `1.x-latest` to solve an [Improper Key Verification vulnerability](https://www.npmjs.com/advisories/1583), as described in [their release page](https://github.com/yaronn/xml-crypto/releases/tag/v2.0.0).
- Bumps version to `1.3.0`

#### Related issues
- connect to #300 

### Checklist

- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by marcosins** [comment]
My changes are in b7384fe and 17842c0, but it looks like the branch is outdated and trying to catch up.

**Comment by dhmlau** [comment]
Here are the steps I usually follow, see if it helps:
```
git clone ${forked repository url}
cd ${repo}
git checkout ${branch user used to open PR}
git remote add upstream ${strongloop repo url}
git remote -v // optional - used to verify remotes you have setup
git fetch upstream
git rebase -i upstream/master
// rebase + re-word / change commit message as usual and exit edit mode
git push origin +${branch you are on -- the one user used to open PR}
```

**Comment by dhmlau** [comment]
And thanks for submitting the PR :)

**Comment by marcosins** [comment]
Thanks you for your git tips.
I got a lot conflicts while rebasing from `master` since it's in version `3.0.0` and I'm submitting this PR for `1.22.1`.

I think `strongloop/strong-soap/1.x-latest` needs to catch up to `strongloop/strong-soap/tag:1.22.1` first and then merge my 2 commits.

**Comment by dhmlau** [comment]
@marcosins, sorry that I just realized you're making changes to `1.x` branch. In this case, after git clone, you can check out the `1.x-latest` branch, and then make changes from there.
What we'd like to get to is just the commits that belong to you. Hope it helps.

**Pull request closed without merging**
