### PR TITLE
Fix #215 Exception on executable built on zeit/pkg

### LINKED ISSUE #215: Error: Cannot find module './src/security/index' - using require('strong-soap') on zeit/pkg builded executable
# Description/Steps to reproduce
Building a packaged executable with [zeit/pkg](https://github.com/zeit/pkg) generates an exception

```
npm install strong-soap --save
add strong-soap with require('strong-soap') in any file
pkg . --out-dir '...any desired output directory after configure pkg'
run executable file
```
Watch the exception:
> Error: Cannot find module './src/security/index'
>1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\snapshot\project-x\node_modules\strong-soap\index.js:10:23)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\snapshot\project-x\index.js:0:0)

# Link to reproduction sandbox
None

# Expected result
Execution without problems

# Additional information
[strong-globalize](https://github.com/strongloop/strong-globalize) will be involved in solution

### PR DESCRIPTION
**Pull request by reajuria**
Fixes #215, "Files" Property should be included for use in zeit/pkg

### Description
PR to fix issue

#### Related issues

- connect to #215 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@reajuria Please sign CLA at https://cla.strongloop.com/agreements/strongloop/strong-soap.

**Comment by raymondfeng** [comment]
@reajuria Please also rebase against upstream/master:

```sh
git remote add upstream git@github.com:strongloop/strong-soap.git
git fetch --all
git rebase upstream/master
git push -f
```

**Comment by reajuria** [comment]
> @reajuria Please also rebase against upstream/master:
> 
> ```shell
> git remote add upstream git@github.com:strongloop/strong-soap.git
> git fetch --all
> git rebase upstream/master
> git push -f
> ```

Hi @raymondfeng I'm done

**Comment by reajuria** [comment]
admins, do you have any comments about this PR?

**Pull request closed without merging**
