### PR TITLE
handle xsd order correctly

### PR DESCRIPTION
**Pull request by bgdavidx**
this makes the xmlbuilder build xml elements in the same order as defined in the xsd file.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rashmihunt** [comment]
@slnode ok to test

**Comment by raymondfeng** [comment]
@bgdavidx Thank you for the patch. I have reworked the implementation in https://github.com/strongloop/strong-soap/commit/3338eb342e0dc263703c23f7b001bb32a1549630.

**Comment by raymondfeng** [comment]
Close it now as the work is available in #144

**Pull request closed without merging**
