### PR TITLE
mark all code blocks in readme.md with their respective type

### PR DESCRIPTION
**Pull request by capaj**
### Description

just a nicer documentation

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
@capaj Thanks for your contribution! Can you amend the commit message to be 50 characters or less so it passes `Commit Linter` and we can get this landed.

**Comment by capaj** [comment]
@virkt25 shortened

**Comment by virkt25** [comment]
@capaj Thanks for your contribution! It has landed 🎉

**Pull request merged**
